Test fail

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -302,7 +302,7 @@ jobs:
             echo ${URL} 
             if curl -s ${URL} | grep "Welcome"
             then
-              exit 0
+              exit 1
             else
               exit 1
             fi
@@ -371,48 +371,48 @@ workflows:
     jobs:
       - build-frontend
       - build-backend
-      - test-frontend:
-          requires: [build-frontend]
-      - test-backend:
-          requires: [build-backend]
-      - scan-frontend:
-          requires: [build-frontend]
-      - scan-backend:
-          requires: [build-backend]
-      - deploy-infrastructure:
-          filters:
-            branches: 
-              only: [master]
-          requires:
-            - build-backend
-            - build-frontend
+      # - test-frontend:
+      #     requires: [build-frontend]
+      # - test-backend:
+      #     requires: [build-backend]
+      # - scan-frontend:
+      #     requires: [build-frontend]
+      # - scan-backend:
+      #     requires: [build-backend]
+      # - deploy-infrastructure:
+      #     filters:
+      #       branches: 
+      #         only: [master]
+      #     requires:
+      #       - build-backend
+      #       - build-frontend
        
-      - configure-infrastructure:
-          requires: [deploy-infrastructure]
-      - run-migrations:
-          requires: [configure-infrastructure]
-      - deploy-frontend:
-          filters:
-            branches: 
-              only: [master]
-          requires: [deploy-infrastructure]
-      - deploy-backend:
-          filters:
-            branches: 
-              only: [master]
-          requires: [run-migrations]
+      # - configure-infrastructure:
+      #     requires: [deploy-infrastructure]
+      # - run-migrations:
+      #     requires: [configure-infrastructure]
+      # - deploy-frontend:
+      #     filters:
+      #       branches: 
+      #         only: [master]
+      #     requires: [deploy-infrastructure]
+      # - deploy-backend:
+      #     filters:
+      #       branches: 
+      #         only: [master]
+      #     requires: [run-migrations]
       - smoke-test:
-          requires: [deploy-frontend, deploy-backend]
-      - cloudfront-update:
-          filters:
-            branches: 
-              only: [master]
-          requires: [smoke-test]
-      - cleanup:
-          filters:
-            branches: 
-              only: [master]
-          requires: [cloudfront-update]
+      #     requires: [deploy-frontend, deploy-backend]
+      # - cloudfront-update:
+      #     filters:
+      #       branches: 
+      #         only: [master]
+      #     requires: [smoke-test]
+      # - cleanup:
+      #     filters:
+      #       branches: 
+      #         only: [master]
+      #     requires: [cloudfront-update]
       
-        # - configure-exporter
+      #   # - configure-exporter
 
